version: '3.8'

services:
  elyos-app:
    build: .
    ports:
      - "80:80"
    volumes:
      # Montage pour le d√©veloppement (facultatif, retirez si prod)
      - ./src:/app/src
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
